### ISSUE TITLE
C# AstroTime constructor fails for year -2300.

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/astronomy#250]
I tried calling the C# version of Astronomy.Seasons(-2300), but the AstroTime constructor caused an exception:

```
Unhandled exception. System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, DateTimeKind kind)
   at CosineKitty.AstroTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second)
   at CosineKitty.Astronomy.FindSeasonChange(Double targetLon, Int32 year, Int32 month, Int32 day)
   at CosineKitty.Astronomy.Seasons(Int32 year)
```

The problem is I'm relying on DateTime to create AstroTime. It should be possible to create AstroTime that is not representable by DateTime.

It would be nice to avoid DateTime as a requirement for AstroTime.ToString() also.

**Comment by cosinekitty** [comment]
[This web page](https://www.tondering.dk/claus/cal/iso8601.php) says we can format BC dates like `-2300-01-01T00:00:00Z`. Also, dates after the year 9999 can be written with an initial `+`.
