### ISSUE TITLE
JS VectorObserver / inverse_terra sometimes fails to converge

### ISSUE THREAD

**Issue by tostt** [cosinekitty/astronomy#347]
There is a possible heisenbug with VectorObserver().
When running the following loop, I end up with the error `Uncaught inverse_terra failed to converge` (for the value `ts=1717780096005`).

```
const body = Astronomy.Body.Sun
for (let ts = 1717780096000; ts <= 1717780096200; ts++) {
   var date = new Date(ts);
   var vect = Astronomy.GeoVector(body, date, true)
   console.log('ts, date, vector', ts, date.valueOf(), vect)
   var point = Astronomy.VectorObserver(vect)
   console.log('point', point)
   console.log('*')
}
```

However, when I change the starting point of the loop, say from 1717780096000 to 1717780096001, the program falls in error later in the loop. Is anyone able to reproduce this error ?

**Comment by cosinekitty** [comment]
Thank you for your bug report! I have confirmed this is a real problem. I am investigating, and will report back here when I have an update.

**Comment by cosinekitty** [comment]
Here is my repro case:

```
$ node --trace-uncaught test vecobs

/home/don/github/astronomy/source/js/astronomy.min.js:130
function inverse_terra(a,b){var c=a[0]*exports.KM_PER_AU,d=a[1]*exports.KM_PER_AU;a=a[2]*exports.KM_PER_AU;var e=Math.hypot(c,d);if(1E-6>e){b=0;var f=0<a?90:-90;a=Math.abs(a)-EARTH_POLAR_RADIUS_KM}else{for(b=exports.RAD2DEG*Math.atan2(d,c)-15*b;-180>=b;)b+=360;for(;180<b;)b-=360;f=Math.atan2(a,e);for(var g,k=0;;){if(10<++k)throw"inverse_terra failed to converge.";c=Math.cos(f);d=Math.sin(f);var h=(EARTH_FLATTENING_SQUARED-1)*EARTH_EQUATORIAL_RADIUS_KM,l=c*c,m=d*d,n=l+EARTH_FLATTENING_SQUARED*m;g=
                                                                                                                                                                                                                                                                                                                                     ^
inverse_terra failed to converge.
Thrown at:
    at inverse_terra (/home/don/github/astronomy/source/js/astronomy.min.js:130:326)
    at VectorObserver (/home/don/github/astronomy/source/js/astronomy.min.js:145:422)
    at VectorObserverTest (/home/don/github/astronomy/generate/test.js:2857:30)
    at main (/home/don/github/astronomy/generate/test.js:3719:16)
    at /home/don/github/astronomy/generate/test.js:3727:14
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at executeUserEntryPoint (node:internal/modules/run_main:86:12)


Node.js v18.18.0
```

**Comment by cosinekitty** [comment]
This commit was not supposed to close the issue. Re-opening now, because there are more changes coming.
